name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          # version number must be string, otherwise 3.10 becomes 3.1
          - os: windows-latest
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "pypy-3.8"
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install --upgrade pip
    - run: python -m pip install -e .[test]
    - run: python -m pytest
